model:
  _target_: reLLMs.model.openai.OpenAIModel
  api_key: OPENAI_API_KEY
  name: gpt-3.5-turbo
  temperature: 0
  max_tokens: 2000
task:
  _target_: reLLMs.task.ceval.CEvalTask
  name: computer_network
  prompt_type: cot
  few_shot: false
logger:
  _target_: reLLMs.logger.logger_util.setup_logger
  exp_name: ${model.name}_${task.name}
  seed: ${seed}
  snapshot_mode: last
  base_log_dir: ${path.log_dir}
  log_tabular_only: true
  prefix: null
  description: null
path:
  root_dir: ${hydra:runtime.cwd}
  log_dir: ${path.root_dir}/logs/
  exp_dir: ${path.root_dir}/exps/
no_gpu: true
which_gpu: 0
seed: 0
