# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by pyrootutils package in `train.py` and `eval.py`
root_dir: ${hydra:runtime.cwd}

# path to log directory
log_dir: ${path.root_dir}/logs/

# path to exp directory
exp_dir: ${path.root_dir}/exps/
